name: Publish
on:
  push:
    tags:
      - "release-*"

env:
  ProjName: FriendlyFires

jobs:
  publish-package:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build
        run: dotnet build ${{ env.ProjName }}/${{ env.ProjName }}.csproj -o Out

      - name : Upload
        uses: actions/upload-artifact@v4.3.5
        with:
          name: ${{ env.ProjName }}
          path: Out

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: Out/**